server:
  port: 8082

spring:
  application:
    name: oficina-execution-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:oficina_execution_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  rabbitmq:
    addresses: ${CLOUDAMQP_URL:amqp://guest:guest@localhost:5672}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2s
          multiplier: 2
          max-interval: 10s
        default-requeue-rejected: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    probes:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
