apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-service
  labels:
    app: execution-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: execution-service
  template:
    metadata:
      labels:
        app: execution-service
      annotations:
        ad.datadoghq.com/execution-service.logs: '[{"source":"java","service":"oficina-execution-service"}]'
    spec:
      containers:
        - name: execution-service
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082
          envFrom:
            - configMapRef:
                name: execution-service-config
            - secretRef:
                name: execution-service-secrets
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_SERVICE
              value: oficina-execution-service
            - name: DD_ENV
              valueFrom:
                configMapKeyRef:
                  name: execution-service-config
                  key: DD_ENV
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 45
            periodSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
